In [1]:
import pandas as pd

In [7]:
dict1 = {
    "name" : ["aravinth","hari","vinoth"],
    "age" : [24,22,23]
}

In [8]:
dict2 = {
    "name" : ["manoj","tharani","gokul"],
    "age" : [22,22,23]
}

In [9]:
dict2

{'name': ['manoj', 'tharani', 'gokul'], 'age': [22, 22, 23]}

In [15]:
print(pd.DataFrame(dict2))

      name  age
0    manoj   22
1  tharani   22
2    gokul   23

In [16]:
dict1["name"]

['aravinth', 'hari', 'vinoth']

In [31]:
df = pd.read_csv("/home/ramanaravinth/DATA SCIENCE/combined_employee_dataset_1.csv")

In [32]:
df.columns

Index(['age', 'years_experience', 'education_level', 'department',
       'performance_score', 'performance_category'],
      dtype='str')

In [33]:
df.isnull().sum()

age                      0
years_experience         5
education_level         32
department              48
performance_score       29
performance_category    61
dtype: int64

In [34]:
df.head()

,age,years_experience,education_level,department,performance_score,performance_category
0,58,23.0,High School,NaN,10.0,Excellent
1,48,39.0,Bachelor,HR,6.0,Good
2,34,NaN,High School,HR,5.0,Average
3,27,29.0,PhD,NaN,4.0,NaN
4,40,36.0,NaN,Finance,2.0,NaN

In [30]:
df.tail()

,age,years_experience,education_level,department,performance_score,performance_category
786,21,19,Bachelor,Sales,9.0,Very Good
787,25,4,Master,Finance,4.0,Average
788,47,35,Bachelor,Finance,6.0,Good
789,47,17,High School,Sales,1.0,Poor
790,39,28,Bachelor,Sales,9.0,Very Good

In [35]:
df.describe()

              age  years_experience  performance_score
count  791.000000        786.000000          762.00000
mean    39.867257         21.017812            5.41601
std     11.867681         11.486117            2.90930
min     20.000000          1.000000            1.00000
25%     29.000000         11.000000            3.00000
50%     41.000000         22.000000            5.00000
75%     51.000000         31.750000            8.00000
max     59.000000         39.000000           10.00000

In [37]:
df.dtypes

age                       int64
years_experience        float64
education_level             str
department                  str
performance_score       float64
performance_category        str
dtype: object

In [46]:
df["age"]

0      58
1      48
2      34
3      27
4      40
       ..
786    21
787    25
788    47
789    47
790    39
Name: age, Length: 791, dtype: int64